//
//  C57_91_Functions.c
//  OverloadTemperatures
//
//  Created by Peter Huber on 2022-12-12.
//

#include "C57_91_Functions.h"
#include <math.h>

/* Function G.1: Hottest-spot temperature

 ΘH = ΘA + ΔΘBO + ΔΘWO/BO + ΔΘH/WO
 
 Where:
 ΘA is the average ambient temperature during the load cycle to be studied, °C
 ΔΘBO is the bottom fluid rise over ambient, °C
 ΔΘWO/BO is the temperature rise of oil at winding hot-spot location over bottom oil, °C
 ΔΘH/WO is the winding hot-spot temperature rise over oil next to hot-spot location, °C
 
 Returns:
 ΘH, which is the winding hottest-spot temperature, °C
 
 */
double Theta_H(double theta_A, double delta_theta_BO, double delta_theta_WOBO, double delta_theta_HWO) {
    
    double result = theta_A + delta_theta_BO + delta_theta_WOBO + delta_theta_HWO;
    
    return result;
}

/* Function G.2: Bottom Oil Temperature
 
 ΘBO = ΘAO - ΔΘTOverB / 2

 Where:
 ΘAO is the average fluid temperature in tank and radiator, °C
 ΔΘTOverB is the ratio of temperature rise of fluid at top of radiator over bottom fluid, °C
 
 Returns:
 ΘBO, which is the bottom fluid temperature, °C
 
 */
double Theta_BO(double theta_AO, double delta_theta_ToverB) {
    
    double result = theta_AO - delta_theta_ToverB / 2.0;
    
    return result;
}

/* Function G.3: Top Oil Temperature
 
 ΘTO = ΘAO + ΔΘTOverB / 2

 Where:
 ΘAO is the average fluid temperature in tank and radiator, °C
 ΔΘTOverB is the ratio of temperature rise of fluid at top of radiator over bottom fluid, °C
 
 Returns:
 ΘTO, which is the top fluid temperature, °C
 
 */
double Theta_TO(double theta_AO, double delta_theta_ToverB) {
    
    double result = theta_AO + delta_theta_ToverB / 2.0;
    
    return result;
}

/* Function G.4: Heat generated by the windings from time t1 to t2
 
 QGEN,W = K^2 (Pw x Kw + Pe / Kw) Δt
 
 Where:
 K is the ratio of load L to rated load, per unit
 Kw is the temperature correction for losses of winding
 Pe is the eddy loss of windings at rated load, W
 Pw is the winding I2R loss at rated load, W
 Δt is the time increment for calculation, min
 
 Returns:
 QGEN,W which is the heat generated by windings, W-min
 
 */
double Q_GEN_w(double K, double Kw, double Pe, double Pw, double delta_T) {
    
    double result = K * K * (Pw * Kw + Pe / Kw) * delta_T;
    
    return result;
}

/* Function G.5 Temperature Correction for Winding Losses
 
 Kw = (ΘW,1 + ΘK) / (ΘW,R + ΘK)
 
 Where:
 ΘK is the temperature factor for resistance correction, °C
 ΘW,1 is the average winding temperature at the prior time, °C
 ΘW,R is the average winding temperature at rated load tested, °C
 
 Returns:
 Kw, which is the temperature correction for losses of winding
 
 */
double Kw(double theta_Wr, double theta_W1, double theta_K) {
    
    double result = (theta_W1 + theta_K) / (theta_Wr + theta_K);
    
    return result;
}

/* Function G.6: The heat lost by the windings
   (NOTE: The standard shows a G.6A for ONAN, ONAF, and OFAF and G.6B for ODAF. We require the cooling type as an input to the routine and call the correct function accordingly).
 
 QLOST,W = ((ΘW,1 - ΘDAO,1) / (ΘW,1 - ΘDAO,R))^5/4 x (μW,R / μW,1)^1/4 x (Pw + Pe) Δt
  
 Where:
 Pe is the eddy loss of windings at rated load, W
 Pw is the winding I2R loss at rated load, W
 ΘDAO,1 is the average temperature of fluid in cooling ducts at the prior time, °C
 ΘDAO,R is the average temperature of fluid in cooling ducts at rated load, °C
 ΘW,1 is the average winding temperature at the prior time, °C
 ΘW,R is the average winding temperature at rated load tested, °C
 Δt is the time increment for calculation, min
 μW,1 is the viscosity of fluid for average winding temperature rise at rated load at the prior time, cP
 μW,R is the viscosity of fluid for average winding temperature rise at rated load, cP
 
 Returns:
 QLOST,W which is the heat lost by winding, W-min
 
 */
double QLOST_W(PCH_CoolingTypes cType, double Pe, double Pw, double theta_DAO1, double theta_DAOR, double theta_W1, double theta_Wr, double delta_T, double mu_W1, double mu_Wr) {
    
    // if the cooling type is ODAF, we ignore the μ values
    double muFactor = 1.0;
    if (cType != ODAF) {
        
        muFactor = pow(mu_Wr / mu_W1, 0.25);
    }
    
    double result = pow((theta_W1 - theta_DAO1) / (theta_Wr - theta_DAOR), 1.25) * muFactor * delta_T;
    
    return result;
}

/* Function G.7: The mass and thermal capacitance of the windings
 
 MWCpW = τW (Pw + Pe) / (ΘW,R - ΘDAO,R)
 
 Where:
 Pe is the eddy loss of windings at rated load, W
 Pw is the winding I2R loss at rated load, W
 ΘDAO,R is the average temperature of fluid in cooling ducts at rated load, °C
 ΘW,R is the average winding temperature at rated load tested, °C
 τW is the winding time constant, min
 
 Returns:
 MWCpW, which is the winding mass times specific heat, W-min/°C
 
 */
double MCp_W(double Pw, double Pe, double tau_W, double theta_DAOR, double theta_Wr) {
    
    double result = tau_W * (Pw + Pe) / (theta_Wr - theta_DAOR);
    
    return result;
}

/* Function G.8: The average winding temperature at time t = t2
 
 ΘW,2 = (QGEN,W - QLOST,W + MWCpW * ΘW,1) / MWCpW
 
 Where:
 MWCpW is the winding mass times specific heat, W-min/°C
 QGEN,W is the heat generated by windings, W-min
 QLOST, W is the heat lost by winding, W-min
 ΘW,1 is the average winding temperature at the prior time, °C
 
 Returns:
 ΘW,2, which is the average winding temperature at the next instant of time, °C
 
 */
double Theta_W2(double QGEN_W, double QLOST_W, double MCp_W, double theta_W1) {
    
    double result = (QGEN_W - QLOST_W + MCp_W * theta_W1) / MCp_W;
    
    return result;
}

/* Function G.9: Winding duct oil temperature rise over bottom oil
 
 ΔΘDO/BO = ΘTDO - ΘBO = ((QLOST,W / (Δt (Pw + Pe))^x)(ΘTDO,R - ΘBO,R)
 
 Where:
 Pe is the eddy loss of windings at rated load, W
 Pw is the winding I2R loss at rated load, W
 QLOST,W is the heat lost by winding, W-min
 x is the exponent for duct oil rise over bottom oil, and is 0.5 for ONAN, ONAF, and OFAF, 1.0 for ODAF
 ΘBO is the bottom fluid temperature, °C
 ΘBO,R is the bottom fluid temperature at rated load, °C
 ΘTDO is the fluid temperature at top of duct, °C
 ΘTDO,R is the fluid temperature at top of duct at rated load, °C
 Δt is the time increment for calculation, min
 
 Returns:
 ΔΘDO/BO is the temperature rise of fluid at top of duct over bottom fluid, °C
 
 */
double Delta_Theta_DOoverBO(double QLOST_W, double x, double delta_T, double Pw, double Pe, double theta_TDOR, double theta_BOR) {
    
    double result = pow(QLOST_W / (delta_T * (Pw + Pw)), x) * (theta_TDOR - theta_BOR);
    
    return result;
}
